# Generated by Django 6.1.1 on 2026-09-07 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='fa-award', help_text='Font Awesome icon class, e.g. fa-award', max_length=40)),
                ('color', models.CharField(default='#e63946', max_length=20)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('donations_required', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['points_required', 'donations_required'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='donors.donorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='rewards.badge')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='donors.donorprofile')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('donor', 'badge')},
            },
        ),
    ]
